what is an array in python and how do we use it
ans : an array in python= numpy which stores values of same data type . In python , this is the main difference between array and lists - while python 
lists can contain values   corresponding to different data types , arrays in  python can only contain values corresponding to same data type 


In [8]:
##importing the library first to use that
import numpy as np 
##creating an array from list 
listt = [1  , 2 ,3 , 4]
#converting into an array 
arr = np.array(listt)
type(arr)


numpy.ndarray

In [18]:
#building an 2D array

print(arr2)
print("the row and coloumn of the array are respectively: ", arr2.shape)

[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]]
the row and coloumn of the array are respectively:  (3, 4)


In [28]:
#testing with row and coloumn
lst1 = [1 , 2, 3]
lst2 = [2, 3, 4, 5]
lst3 = [5, 6 , 7 ,7 , 8]
arrImplementation = np.array(lst1 , lst2, lst3)# this will give out errors

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [46]:
#indexing an array to retrieve an element from the array

arr12 = np.array([1, 2, 23, 5])
print(arr12)
arr12[3] #this wil print the index
arr12[0:3] #will take index 0 ,1 ,2

[ 1  2 23  5]


array([ 1,  2, 23])

In [60]:
#reversin g the elements in the array
lst = [1,3,45,56]
arrr= np.array(lst[::-1])
print(arrr)
arrr[:-1]

[56 45  3  1]


array([56, 45,  3])

In [83]:
#indexing in 2D array
#creating a 2D array first 
lst1 = [ 1, 2, 3, 4]
lst2 = [2 , 3, 4, 5]
lst3 = [5, 6, 7, 8]

#making a nested list 
arr2 = np.array([lst1 , lst3 , lst2])
print(arr2)
#indexing in the arr2
arr2[:,1] #this should print : = all the rous selected and 1 = coloumn 1 should be selected 


[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]]


array([2, 6, 3])

In [102]:
#printting lets say from the arr2  using indexing
#goal to print
'''
([6 ,7]
[3,4])
'''
print(arr2[1: , 1:3]) 

'''
trying to print
([3,4]
[7,8]
[4.5])
'''
print("the output  would be printed like this ")
arr2[: , 2:] #meaning is since before "," is row so in the row gap we have added ":" means all the rows and in the coloumn we have "2:" means from the 2nd index to the ast coloumn index 

[[6 7]
 [3 4]]
the output  would be printed like this 


array([[3, 4],
       [7, 8],
       [4, 5]])

In [113]:
#in 2D array we can do the  broadcasting very well lets look into that for a bit
#lets make an array 2D first
'''
we have the arr2 with the 4 coloumns and 3 rows
[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]]
 its (3 , 4)

  its a 12 matrix array 
'''

##lets reshape it first 
arr2Reshaped = arr2.reshape(4,3)
print(arr2Reshaped)#just reversed the rows and coloumns

[[1 2 3]
 [4 5 6]
 [7 8 2]
 [3 4 5]]


In [123]:
'''
multipleying an array 
'''

print(arr*2)
print(arr2*2)
print(arr2*arr2)

[2 4 6 8]
[[ 2  4  6  8]
 [10 12 14 16]
 [ 4  6  8 10]]
[[ 1  4  9 16]
 [25 36 49 64]
 [ 4  9 16 25]]


In [129]:
#ones method return an array with only ones
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [131]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [155]:
#randint does generate a array wuith randowm value when provided wit h only the high and low values
np.random.randint(12 , 809,4).reshape(2,2) # (low value , high value ,, no of elements generated) then shaping it 2*2 = size  or the no of elemennts genrated

array([[665, 506],
       [138, 696]])

In [153]:
#generating from standard normal distribution
np.random.randn(5,6)

array([[-0.24409632,  0.78429473, -1.48639299,  1.28865677, -0.15251666,
         0.0554551 ],
       [ 1.30168323, -1.05438292, -1.66483036, -1.44485832, -0.84896752,
         0.88626784],
       [-0.20912544,  0.60124027, -1.27883251,  0.30051868, -0.17986533,
         0.39312739],
       [ 0.62235935,  0.45884198, -1.10387166,  0.43203495, -0.89460789,
         1.96149171],
       [ 0.10125599,  0.06860199,  0.94546545, -0.92549926, -0.25802948,
        -1.11181068]])